version: '3.7'

services:
    php-httpd:
        image: php:7.3-apache
        ports:
            - 8081:80
        volumes:
            - ".:/var/www/html"

    mariadb:
        image: mariadb:10.5.2
        volumes:
            - .:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "Acesso#01"
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'Acesso#01'
            MYSQL_DATABASE: 'laravel'

volumes:
    mariadb-volume:
